### ISSUE TITLE
Run getting halted in between with error code b

### ISSUE THREAD

**Issue by aryasuresh234** [phac-nml/ecoli_serotyping#77]
Hi can you please help me resolve the following error?
2019-11-29 23:41:27,445 ectyper.speciesIdentification INFO     GCF_001672015
2019-11-29 23:41:27,535 ectyper.subprocess_util ERROR    Error in subprocess. The following command failed: ['grep', 'GCF_001672015', '/home/arya/miniconda3/lib/python3.7/site-packages/ectyper/Data/assembly_summary_refseq.txt']
2019-11-29 23:41:27,538 ectyper.subprocess_util ERROR    Subprocess failed with error: b''
2019-11-29 23:41:27,539 ectyper.subprocess_util CRITICAL ectyper has stopped
subprocess failure
-Arya

**Comment by kbessonov1984** [comment]
@aryasuresh234 Hello Arya! This issue has to do with the `grep` inability to map accession number to the species identification. As a temporal solution please replace `/home/arya/miniconda3/lib/python3.7/site-packages/ectyper/Data/assembly_summary_refseq.txt` with the `ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/assembly_summary_genbank.txt` containing a complete set of accession numbers. Rename downloaded file to the `assembly_summary_refseq.txt` and place it in `/home/arya/miniconda3/lib/python3.7/site-packages/ectyper/Data` directory (overwriting the old one if necessary).
 
I found that sometimes some RefSeq accessions are removed from RefSeq database causing this issue to popup. In the future version `0.9.1` will be addressing this issue giving user a warning if no match is found (i.e. species identification fails). 

Let me know if it solved your issue for now.

**Comment by aryasuresh234** [comment]
Hello Kirill
Thanks for getting back to me so quickly on this. I have tried the method you suggested to me. But the error seems to be not resolved, it's popping up again, this time with a different file name this time:
2019-12-01 01:46:12,094 ectyper.speciesIdentification INFO     GCF_900092915
2019-12-01 01:46:12,224 ectyper.subprocess_util ERROR    Error in subprocess. The following command failed: ['grep', 'GCF_900092915', '/home/arya/miniconda3/lib/python3.7/site-packages/ectyper/Data/assembly_summary_refseq.txt']
2019-12-01 01:46:12,225 ectyper.subprocess_util ERROR    Subprocess failed with error: b''
2019-12-01 01:46:12,225 ectyper.subprocess_util CRITICAL ectyper has stopped
subprocess failure
Can you please have a look
-Arya

**Comment by kbessonov1984** [comment]
@aryasuresh234 Hi Arya. Sorry to hear that the fix did not completely work for you. Will make it work asap as it is critical issue. We need to make sure that accession numbers of the MASH sketch are completely represented in the meta data assembly_summary file.

Have you replaced the `assembly_summary_refseq.txt` file with the `assembly_summary_genbank.txt` and renamed it to `assembly_summary_refseq.txt`? I will address this issue this week by releasing a new version of the tool, but for a quick fix make sure your  `assembly_summary_refseq.txt` file is 160 MB in size (i.e. downloaded completely), was renamed to `assembly_summary_refseq.txt` and is in `home/arya/miniconda3/lib/python3.7/site-packages/ectyper/Data/` folder. What do you get when you run grep on this file? I.e. `grep "GCF_001672015" home/arya/miniconda3/lib/python3.7/site-packages/ectyper/Data/assembly_summary_refseq.txt`?



Here is what I get on my end. The accession number `GCF_001672015` was removed from the RefSeq database due to contamination, but MASH Sketch still has this reference causing the species identification to fail.

```
grep "GCF_001672015" assembly_summary_genbank.txt
GCA_001672015.1	PRJNA321990	SAMN04963292		na	562	562	Escherichia coli		Co6114	latest	Chromosome	Major	Full	2016/06/20	ASM167201v1	University Medical Center Hamburg-Eppendorf	GCF_001672015.1	identical	ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/672/015/GCA_001672015.1_ASM167201v1	contaminated
```

**Comment by kbessonov1984** [comment]
The version 0.9.1 should resolve completely the issue of null `grep` output when searching for RefSeq accession in the meta data.
