### ISSUE TITLE
Can you please explain the QC?

### ISSUE THREAD

**Issue by samlipworth** [phac-nml/ecoli_serotyping#81]
00104c81-2985-4943-9502-9143a1eee412	Escherichia coli UMEA 3053-1	O75	H5	O75:H5	NA	-	Based on 3 allele(s)	wzx:1.000;wzy:1.000;fliC:1.000;	-
0013e2ce-394b-4fc5-a356-abadd635fa00	Escherichia coli 2-177-06_S4_C2	O132	H10	O132:H10	NA	-	Based on 3 allele(s)	wzx:0.999;wzy:0.999;fliC:1.000;	-

Eg the two records above - the QC column is NA, confidence -   output looks sensible against eg MLST though - can you explain how EcTyper does this and what the above means?

Thanks

**Comment by kbessonov1984** [comment]
@samlipworth . The QC column is for testing purposes so far. The reason why you've did not get any values is because you run without `--verify` parameter which checks for sample to be of E.coli species and updates species column to Escherichia coli value. Since species check is done using exact match, the QC module considered these samples as non-E.coli and refused to output any QC assessment values. I should of used regular expression instead of an exact value match. I am currently working on version 1.0 which will have much better and sensible QC module where prediction accuracy and sensitivity are the main targets. Please run the tool with the `--verify` parameter to get QC values.

In current version 0.9.1 the QC module provides very vague idea of the result confidence and is based on our empirical data. For version 1.0.0 we are currently doing much thorough QC analyses to arrive at min quality values for each antigen to be confidently resolved (if possible at all).

1. If aggregate mean score across O and H antigen is >= 0.95 you get PASS value and HIGH confidence value.
1. If aggregate mean score across O and H antigen is between 0.80 and 0.95 you get PASS value and MEDIUM confidence value 
For other definitions look at https://github.com/phac-nml/ecoli_serotyping/blob/a7e67b6df13c018b4b3348635220bef074557606/ectyper/predictionFunctions.py#L258

**Comment by samlipworth** [comment]
Thanks very much for this - does this use the Serotypefinder database / what should I cite when using this tool?

**Comment by kbessonov1984** [comment]
Hello,
We just released version 1.0.0 with the QC module that is different from the version 0.9.1. The QC module is designed mostly for reference services to understand if a given antigen call (e.g. O157) is reliable enough to get reported or needs additional wet-lab verification. The reliability was calculated as a function of minimum %id and %cov to prevent false hits against other antigens (i.e. cross-talk) based on the alleles database. E.g. some antigens like O17 fall into high similarity group and even at 99% identity and 100% coverage can give cross hits with O77, O73 and O106. Others like O157 require coverage of only 5% to successfully unambiguously resolve.
In new README there is a table at the bottom that explains all QC values. If coverage is good and antigen is not part of one of the high similarity groups, then you will get PASS (REPORTABLE) QC value. If O antigen call is mixed, then you will get a warning (WARNING MIXED O-TYPE) since this antigen could not be resolved to a single call. This does not mean that it is a fail. It just means that it is a mixed prediction and requires end-user call. We plan to expand on resolution power of the tool using other genes or other approaches in future, but it is a complex task as wet-lab results might also be misleading due to anti-sera cross-reactivity, etc.

The manuscript is currently in preparation and results section is almost complete. We plan to submit at the end of summer. For now refer to this repository (it is possible to cite repository).

Thanks for reaching out

**Comment by samlipworth** [comment]
Thanks this is all very helpful. Can you just confirm what the underlying allele reference database is - was this developed bespoke by you for this project or does it use another reference database eg. Serotypefinder?

**Comment by kbessonov1984** [comment]
The reference alleles database is in JSON format and was developed both by us and by merging SerotypeFinder and SRST2 databases.  You can take a look at the `ectyper_alleles_db.json` file stored in `Data` folder. Most of the alleles come from EnteroBase E.coli samples and those have `ESC_` accession numbers mentioned in description field. Most E.coli serotyping tools use identical NCBI deposited references.  By sequencing reference strains we found that antigen alleles are identical to references already available in NCBI. Thus all alleles are from public sources. In future we might add a couple of internal allele references for poorly represented antigens like O90.

**Comment by samlipworth** [comment]
Perfect thanks a lot that explains everything!
