### ISSUE TITLE
Refseq currency check ignores the -r (--refseq) argument

### ISSUE THREAD

**Issue by fda-rapid-cfsan-rge** [phac-nml/ecoli_serotyping#84]
When using the -r (or --refseq) option, the database currency check nonetheless still uses the default location (__file__/Data/).  Consequence:  users get a write permission error and ectyper abends.

In def get_refseq_mash():
.
.
.
    targetpath = os.path.join(os.path.dirname(__file__),"Data/refseq.genomes.k21s1000.msh")

    if bool_downloadMashRefSketch(targetpath):

**Comment by kbessonov1984** [comment]
@fda-rapid-cfsan-rge Thank you for reporting this issue. I am about to release the final publication version of the tool next week and will address the issue. I will remove NCBI genomes database age checks as after testing in read-only contexts on public Galaxy Instances (e.g. Galaxy Europe where ECTyper is currently hosted) a race condition and database update would fail. I will re-release patched version 1.0.0 and update here.

**Comment by kbessonov1984** [comment]
@fda-rapid-cfsan-rge  Had updated code and removed recency check for the MASH RefSeq sketch and associated assembly data checks. This is unnecessary feature and gives more issues than any benefits (i.e. species resolution). I re-released version 1.0 and will update conda build for version 1.0.0 which will do automatic `Data/` folder update upon conda install. Otherwise it is possible now to install `ectyper` via `pip` but software init will be done upon first run (which might create a race condition). Therefore new conda install is recommended.
